apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        image: deletus/backend:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-v1-service
  namespace: prod
spec:
  selector:
    app: backend
    version: v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
