apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
      - name: backend
        image: deletus/backend:v2
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-v2-service
  namespace: dev
spec:
  selector:
    app: backend
    version: v2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
