apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v4
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v4
  template:
    metadata:
      labels:
        app: backend
        version: v4
    spec:
      containers:
      - name: backend
        image: deletus/backend:v4
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-v4-service
  namespace: dev
spec:
  selector:
    app: backend
    version: v4
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
