apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v5
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v5
  template:
    metadata:
      labels:
        app: frontend
        version: v5
    spec:
      containers:
      - name: frontend
        image: deletus/frontend:v5
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-v5-service
  namespace: dev
spec:
  selector:
    app: frontend
    version: v5
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
