apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-git-v1
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-git
      version: v1
  template:
    metadata:
      labels:
        app: frontend-git
        version: v1
    spec:
      containers:
      - name: frontend-git
        image: deletus/frontend-git:1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-git-v1-service
  namespace: prod
spec:
  selector:
    app: frontend-git
    version: v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
