FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the working directory
COPY . .

# Expose the port your app runs on
EXPOSE 5000

# Change directory to src where the server.js is located
WORKDIR /app/src

# Command to run your application
CMD ["node", "server.js"]
